langage: php
php:
    - '7.4'

install:
    - composer install

cache:
    directories:
        - ./vendor

script:
    - php vendor/bin/phpcs -s
    - php bin/console doctrine:schema:update --env=test --force
    - php bin/phpunit
